name: Nextjs Build Export

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Step Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'


      - name: Checkout
        uses: actions/checkout@4

      - name: Install Dependencies
        run : npm install

      - name: Build
        run : npm run build

      - name: Verify the output Folder
        run : ls -l out

      - name: Uplaod Artifact
        uses: actions/uplaod-artifact@v4
        with:
          name: NEWPROJECT Build package
          path : out

      - name: Install Netlify CLI
        run : npm install -g netlify-cli

      - name: Deploy to netlify
        run: |
          netlify deploy --prod \
            --dir=out   \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_USER_TOKEN }}


