name: NEXTJS Build Export


on:
  push:
    branches:
      - main

jobs:
  build:
    name: job1
    runs-on: ubentu-latest
      steps:
        - name: Checkout
          run : actions/checkout@4

        - name: Install Netlify CLI
          run : npm install -g netlify-cli

        - name: Deploy to netlify
          run: |
            netlify deploy --prod \
                --dir=. \
                --site ${{ secrets.NETLIFY_SITE_ID }} \
                --auth ${{ secrets.NETLIFY_USER_TOKEN }}